before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: FMw4IUCGSwiRZRlCO2LYh3mrUwt5USyTUQAmEEWsXYs44loPgqVaQ58Qo+OnyswrJO8Fkbp9Biixk0QvK1NdUxi8DPyw0feyGOC1rkz1J1YWFIOXRx11ZVGzmaOYQ1oafOZFfdR9OLwrLQ/QvkkKwC1OODiFXX9zjSvFWK/uFQKUCTo6fRUwloIq5lnWr4vS9N98LeXuO7ODxWZ+tB9+OTpbnvCLS1ct6Ry1IjerwxEObfurz8NfWbXyzGfm3fyFbxNGXJXtXWGgWVUUyOmDh7xdYqi1b0oIWQvH38tJVfChNi0tSSkvx//pXCjYWVZ6MUCDgUSEy5REVWJ/6nac3aWtxEJt+Ay6AqrpbHrC0XWIMY4yiHxfwqDK3nbxU4YtYfj8/FzeKtN+fkNqfcMGzFr+GyVfEW39FCjuLVUD+nba/uBnq2bQj9y8em2porfIT5SiO+uZifwUt8TZpq4CYZNt0uA6tYr4WGNrC05lUmxvdzvvtA9OR9On9a3ipw5d5cTC+NVCjhYlTe+kDXCXoll5r1UHNsgeXOuyTUiYWD1CANpK2dlu+zClsKV0QpYXd1fh5R7SW4jAgzyUY/rEQL9DmCI0+9F+UWkTz21/Btbg3NUKNeHWB0Y982RzvU/UCIhKh2KEut20bYZb5AS4D2fo/0tv2J2fo2eTwtSkvv0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
